"""Add local_model_path to base_models

Revision ID: 0c62556b8850
Revises: f8eef7042623
Create Date: 2026-02-16 14:36:06.511688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c62556b8850'
down_revision: Union[str, Sequence[str], None] = 'f8eef7042623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('base_models', sa.Column('local_model_path', sa.String(length=500), nullable=True))

    # Copy data from model_download_link to local_model_path for existing rows
    op.execute("UPDATE base_models SET local_model_path = model_download_link WHERE model_download_link IS NOT NULL")

    # Make it NOT NULL now that it has data
    op.alter_column('base_models', 'local_model_path', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('base_models', 'local_model_path')
    # ### end Alembic commands ###
